# -- ACTUAL DATA --

# timestamp for logging
int8 timestamp
string date_time

# data from the 3D Printer
float32 temp_tool1_actual
float32 temp_tool2_actual
float32 temp_bed_actual

# data from the file to be printed
string file_name
string printer3d_state
float32 progress
float32 estimated_time

# -- GOAL DATA --

# data from the 3D Printer
float32 temp_tool1_goal
float32 temp_tool2_goal
float32 temp_bed_goal


